esphome:
  name: "rotary-knob-touch-display-b"

esp32:
  # ESP32-U4WDH (revision v3.1)
  # Wi-Fi, BT, Dual Core + LP Core, 240MHz, Embedded Flash, Vref calibration in eFuse, Coding Scheme None
  # flash size: 4MB
  variant: esp32
  cpu_frequency: 240MHz
  flash_size: 4MB
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

uart:
  - id: uart_interlink_gpio23
    tx_pin: GPIO23
    rx_pin: GPIO18
    baud_rate: 115200
    debug:
      direction: RX
      dummy_receiver: true
      after:
        delimiter: "\n"
      sequence:
        - lambda: |-
            UARTDebug::log_string(direction, bytes);

interval:
  - interval: 60s
    then:
      - uart.write:
          id: uart_interlink_gpio23
          data: "PONG\n"

binary_sensor:
  - id: sensor_rotary_knob_cw_gpio19
    platform: gpio
    pin:
      number: GPIO19
      inverted: true
    on_release:
      lambda: |-
        ESP_LOGD("sensor_rotary_knob_cw_gpio19", "rotate clockwise");
  - id: sensor_rotary_knob_ccw_gpio22
    platform: gpio
    pin:
      number: GPIO22
      inverted: true
    on_release:
      lambda: |-
        ESP_LOGD("sensor_rotary_knob_ccw_gpio22", "rotate counter-clockwise");

