esphome:
  name: "rotary-knob-touch-display-a"

esp32:
  # ESP32-S3 (QFN56) (revision v0.2)
  # Wi-Fi, BT 5 (LE), Dual Core + LP Core, 240MHz, Embedded PSRAM 8MB (AP_3v3)
  # flash size: 16MB
  variant: esp32s3
  cpu_frequency: 240MHz
  flash_size: 16MB
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  manual_ip:
    static_ip: !secret ipv4_static_ip_a
    gateway: !secret ipv4_gateway
    subnet: !secret ipv4_subnet

i2c:
  - id: i2c_gpio11
    sda: GPIO11
    scl: GPIO12
    scan: true
    # devices: 0x15, 0x5A
